application: captain-scarlet
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /admin
  script: main.app
  login: admin
- url: /.*
  script: main.app
