application: captain-scarlet
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: flask
  version: "0.12"

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.APP
  